# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Generator.ui'
#
# Created: Wed Jan  9 17:40:52 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 720)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.simulateButton = QtGui.QPushButton(self.centralWidget)
        self.simulateButton.setGeometry(QtCore.QRect(810, 670, 180, 20))
        self.simulateButton.setObjectName(_fromUtf8("simulateButton"))
        self.ModelsTab = QtGui.QTabWidget(self.centralWidget)
        self.ModelsTab.setGeometry(QtCore.QRect(810, 10, 180, 550))
        self.ModelsTab.setAutoFillBackground(False)
        self.ModelsTab.setTabShape(QtGui.QTabWidget.Rounded)
        self.ModelsTab.setTabsClosable(False)
        self.ModelsTab.setObjectName(_fromUtf8("ModelsTab"))
        self.OCTab = QtGui.QWidget()
        self.OCTab.setObjectName(_fromUtf8("OCTab"))
        self.experimentsCombo = QtGui.QComboBox(self.OCTab)
        self.experimentsCombo.setGeometry(QtCore.QRect(10, 30, 155, 20))
        self.experimentsCombo.setObjectName(_fromUtf8("experimentsCombo"))
        self.experimentPropertiesGroupBox = QtGui.QGroupBox(self.OCTab)
        self.experimentPropertiesGroupBox.setGeometry(QtCore.QRect(10, 60, 155, 391))
        self.experimentPropertiesGroupBox.setObjectName(_fromUtf8("experimentPropertiesGroupBox"))
        self.propertiesScrollArea = QtGui.QScrollArea(self.experimentPropertiesGroupBox)
        self.propertiesScrollArea.setGeometry(QtCore.QRect(10, 20, 140, 371))
        self.propertiesScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.propertiesScrollArea.setWidgetResizable(True)
        self.propertiesScrollArea.setObjectName(_fromUtf8("propertiesScrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 138, 369))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.propertiesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.propertiesLabel.setGeometry(QtCore.QRect(0, 10, 131, 351))
        self.propertiesLabel.setText(_fromUtf8(""))
        self.propertiesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.propertiesLabel.setObjectName(_fromUtf8("propertiesLabel"))
        self.propertiesScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.experimentsLabel = QtGui.QLabel(self.OCTab)
        self.experimentsLabel.setGeometry(QtCore.QRect(10, 10, 155, 20))
        self.experimentsLabel.setObjectName(_fromUtf8("experimentsLabel"))
        self.loadExpermientButton = QtGui.QPushButton(self.OCTab)
        self.loadExpermientButton.setGeometry(QtCore.QRect(10, 460, 151, 23))
        self.loadExpermientButton.setObjectName(_fromUtf8("loadExpermientButton"))
        self.newExperimentButton = QtGui.QPushButton(self.OCTab)
        self.newExperimentButton.setGeometry(QtCore.QRect(10, 490, 151, 23))
        self.newExperimentButton.setObjectName(_fromUtf8("newExperimentButton"))
        self.ModelsTab.addTab(self.OCTab, _fromUtf8(""))
        self.WindowTab = QtGui.QWidget()
        self.WindowTab.setObjectName(_fromUtf8("WindowTab"))
        self.ModelsTab.addTab(self.WindowTab, _fromUtf8(""))
        self.ScrollX = QtGui.QScrollBar(self.centralWidget)
        self.ScrollX.setGeometry(QtCore.QRect(30, 670, 760, 20))
        self.ScrollX.setProperty("value", 0)
        self.ScrollX.setSliderPosition(0)
        self.ScrollX.setOrientation(QtCore.Qt.Horizontal)
        self.ScrollX.setObjectName(_fromUtf8("ScrollX"))
        self.ScrollY = QtGui.QScrollBar(self.centralWidget)
        self.ScrollY.setGeometry(QtCore.QRect(10, 10, 20, 660))
        self.ScrollY.setOrientation(QtCore.Qt.Vertical)
        self.ScrollY.setInvertedAppearance(True)
        self.ScrollY.setObjectName(_fromUtf8("ScrollY"))
        self.ZoomInButton = QtGui.QPushButton(self.centralWidget)
        self.ZoomInButton.setGeometry(QtCore.QRect(830, 610, 20, 20))
        self.ZoomInButton.setObjectName(_fromUtf8("ZoomInButton"))
        self.ZoomOutButton = QtGui.QPushButton(self.centralWidget)
        self.ZoomOutButton.setGeometry(QtCore.QRect(810, 610, 20, 20))
        self.ZoomOutButton.setObjectName(_fromUtf8("ZoomOutButton"))
        self.FixedRatioCheckBox = QtGui.QCheckBox(self.centralWidget)
        self.FixedRatioCheckBox.setGeometry(QtCore.QRect(860, 610, 150, 20))
        self.FixedRatioCheckBox.setAcceptDrops(False)
        self.FixedRatioCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FixedRatioCheckBox.setChecked(False)
        self.FixedRatioCheckBox.setAutoRepeat(False)
        self.FixedRatioCheckBox.setAutoExclusive(False)
        self.FixedRatioCheckBox.setTristate(False)
        self.FixedRatioCheckBox.setObjectName(_fromUtf8("FixedRatioCheckBox"))
        self.graphCheckBox = QtGui.QCheckBox(self.centralWidget)
        self.graphCheckBox.setGeometry(QtCore.QRect(860, 580, 120, 20))
        self.graphCheckBox.setObjectName(_fromUtf8("graphCheckBox"))
        self.daysBox = QtGui.QSpinBox(self.centralWidget)
        self.daysBox.setGeometry(QtCore.QRect(810, 640, 80, 22))
        self.daysBox.setMinimum(1)
        self.daysBox.setMaximum(2147483646)
        self.daysBox.setProperty("value", 3)
        self.daysBox.setObjectName(_fromUtf8("daysBox"))
        self.daysLabel = QtGui.QLabel(self.centralWidget)
        self.daysLabel.setGeometry(QtCore.QRect(890, 640, 46, 20))
        self.daysLabel.setObjectName(_fromUtf8("daysLabel"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionCoordinateSystem = QtGui.QAction(MainWindow)
        self.actionCoordinateSystem.setObjectName(_fromUtf8("actionCoordinateSystem"))
        self.actionWahrscheinlichkeiten = QtGui.QAction(MainWindow)
        self.actionWahrscheinlichkeiten.setObjectName(_fromUtf8("actionWahrscheinlichkeiten"))
        self.menuOptions.addAction(self.actionCoordinateSystem)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.ModelsTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Profilgenerator", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButton.setText(QtGui.QApplication.translate("MainWindow", "Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.experimentPropertiesGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.experimentsLabel.setText(QtGui.QApplication.translate("MainWindow", "Expermients", None, QtGui.QApplication.UnicodeUTF8))
        self.loadExpermientButton.setText(QtGui.QApplication.translate("MainWindow", "Load Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.newExperimentButton.setText(QtGui.QApplication.translate("MainWindow", "New Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.ModelsTab.setTabText(self.ModelsTab.indexOf(self.OCTab), QtGui.QApplication.translate("MainWindow", "Occupancy", None, QtGui.QApplication.UnicodeUTF8))
        self.ModelsTab.setTabText(self.ModelsTab.indexOf(self.WindowTab), QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.ZoomInButton.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.ZoomOutButton.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.FixedRatioCheckBox.setText(QtGui.QApplication.translate("MainWindow", "fixed ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.graphCheckBox.setText(QtGui.QApplication.translate("MainWindow", "keep old graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.daysLabel.setText(QtGui.QApplication.translate("MainWindow", "Days", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCoordinateSystem.setText(QtGui.QApplication.translate("MainWindow", "Coordinate System", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWahrscheinlichkeiten.setText(QtGui.QApplication.translate("MainWindow", "Wahrscheinlichkeiten", None, QtGui.QApplication.UnicodeUTF8))

